version: '3.7'

services:
  db:
    image: mongo:latest
    container_name: db_pingeso
    environment:
      - MONGO_INITDB_DATABASE=dashbork
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pingeso
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
        # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - certs:/etc/certs/
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/web/static
      - config/:/etc/nginx/conf.d
      - certs:/etc/certs/
    depends_on:
      - webapp
volumes:
  static_volume:
  config:
  certs:
    driver: local
    driver_opts:
      type: none
      device: nginx/config/
      o: bind
  mongodb:
  mongoconfig: